### ISSUE TITLE
Pre Compiled Version unable to execute

### ISSUE THREAD

**Issue by FloppyRooster** [Stem-LG/LimitBat#2]
I downloaded the V0.5-beta.1 and running script attempts to grab files from a non-existent directory.
I.e. the error reads 

"/usr/bin/env: ‘/opt/limitbat/limitbat’: No such file or directory"

Running kubuntu 22.04.

**Comment by Stem-LG** [comment]
@FloppyRooster 
you need to copy limitbat folder into /opt/
cd into the extracted folder then
run `sudo cp -R . /opt/limitbat`

**Comment by Stem-LG** [comment]
you found a good bug btw, thx

you can find the new fixed version here:
https://github.com/Stem-LG/LimitBat/releases/tag/BETA.2
