### ISSUE TITLE
Hard Coded file paths are incorrect

### ISSUE THREAD

**Issue by FloppyRooster** [Stem-LG/LimitBat#3]
Looking through the source code and it was makes reference to some files that don't exist on my system:

"final tempLimitFile = File('/sys/class/power_supply/BAT0/charge_control_end_threshold');
final permLimitFile = File('/etc/systemd/system/bat-boot.service');"

Unfortunately on my system neither of these files exist. I'm not sure what defines the file structure but if the intention is for this program to work on a range of systems, which is not necessarily a good idea, it will have to be changed.

But I'm probably jumping the gun, this project is in its early stages and I don't have enough experience with dart or linux to be more helpful.

This is the contents of "/sys/class/power_supply/BAT0/subsystem/BAT0" if it helps. And all of the files that may be helpful are saved in their raw form and not as a percentage.
![image](https://user-images.githubusercontent.com/86031297/171998727-535a3fd6-f6e1-4e42-b13b-eef8c906202b.png)

Awesome project regardless keep it up!

**Comment by Stem-LG** [comment]
sadly i don't think your laptop supports limiting charging on linux 

as i said it's only for "some" asus laptops that support the feature, not all

but I might be wrong so, you can try this:
https://github.com/tshakalekholoane/bat
or:
https://github.com/linrunner/TLP

and maybe plz tell me if they work so i might investigate how they do it and add it :)
